INSERT INTO poll (poll_id, question) VALUES (1, 'What is your favorite Netflix series?');
INSERT INTO poll (poll_id, question) VALUES (2, 'What is your least favorite Netflix series??');
INSERT INTO poll (poll_id, question) VALUES (3, 'What is your favorite color?');
INSERT INTO poll (poll_id, question) VALUES (4, 'What is your least favorite color?');
INSERT INTO poll (poll_id, question) VALUES (5, 'What is your favorite movie?');
INSERT INTO poll (poll_id, question) VALUES (6, 'What is your least favorite movie?');
INSERT INTO poll (poll_id, question) VALUES (7, 'What is your favorite book?');
INSERT INTO poll (poll_id, question) VALUES (8, 'What is your lease favorite book?');
INSERT INTO poll (poll_id, question) VALUES (9, 'What is your favorite food?');
INSERT INTO poll (poll_id, question) VALUES (10, 'What is your least favorite food?');
INSERT INTO poll (poll_id, question) VALUES (11, 'What is your favorite drink?');
INSERT INTO poll (poll_id, question) VALUES (12, 'What is your least favorite drink?');
INSERT INTO poll (poll_id, question) VALUES (13, 'What is your favorite athlete?');
INSERT INTO poll (poll_id, question) VALUES (14, 'What is your least favorite athlete?');
INSERT INTO poll (poll_id, question) VALUES (15, 'What is your favorite music genre?');
INSERT INTO poll (poll_id, question) VALUES (16, 'What is your least favorite music genre?');
INSERT INTO poll (poll_id, question) VALUES (17, 'What is your favorite city?');
INSERT INTO options (options_id, options_value, poll_id) VALUES (1, 'Stranger Things', 1);
INSERT INTO options (options_id, options_value, poll_id) VALUES (2, 'Black Mirror', 1);
INSERT INTO options (options_id, options_value, poll_id) VALUES (3, 'The Getdown', 1);
INSERT INTO options (options_id, options_value, poll_id) VALUES (4, 'Orange Is the New Black', 1);
INSERT INTO options (options_id, options_value, poll_id) VALUES (5, 'Stranger Things', 2);
INSERT INTO options (options_id, options_value, poll_id) VALUES (6, 'Black Mirror', 2);
INSERT INTO options (options_id, options_value, poll_id) VALUES (7, 'The Getdown', 2);
INSERT INTO options (options_id, options_value, poll_id) VALUES (8, 'Orange Is the New Black', 2);
INSERT INTO options (options_id, options_value, poll_id) VALUES (9, 'Red', 3);
INSERT INTO options (options_id, options_value, poll_id) VALUES (10, 'Blue', 3);
INSERT INTO options (options_id, options_value, poll_id) VALUES (11, 'Yellow', 3);
INSERT INTO options (options_id, options_value, poll_id) VALUES (12, 'Red', 4);
INSERT INTO options (options_id, options_value, poll_id) VALUES (13, 'Blue', 4);
INSERT INTO options (options_id, options_value, poll_id) VALUES (14, 'Yellow', 4);
INSERT INTO options (options_id, options_value, poll_id) VALUES (15, 'Star Wars', 5);
INSERT INTO options (options_id, options_value, poll_id) VALUES (16, 'The Matrix', 5);
INSERT INTO options (options_id, options_value, poll_id) VALUES (17, 'The Avengers', 5);
INSERT INTO options (options_id, options_value, poll_id) VALUES (18, 'Star Wars', 6);
INSERT INTO options (options_id, options_value, poll_id) VALUES (19, 'The Matrix', 6);
INSERT INTO options (options_id, options_value, poll_id) VALUES (20, 'The Avengers', 6);
INSERT INTO options (options_id, options_value, poll_id) VALUES (21, 'Bible', 7);
INSERT INTO options (options_id, options_value, poll_id) VALUES (22, 'One Hundred Years Of Solitude', 7);
INSERT INTO options (options_id, options_value, poll_id) VALUES (23, 'Game of Thrones', 7);
INSERT INTO options (options_id, options_value, poll_id) VALUES (24, 'Bible', 8);
INSERT INTO options (options_id, options_value, poll_id) VALUES (25, 'One Hundred Years of Solitude', 8);
INSERT INTO options (options_id, options_value, poll_id) VALUES (26, 'Game of Thrones', 8);
INSERT INTO options (options_id, options_value, poll_id) VALUES (27, 'Pizza', 9);
INSERT INTO options (options_id, options_value, poll_id) VALUES (28, 'French fries', 9);
INSERT INTO options (options_id, options_value, poll_id) VALUES (29, 'Ice cream', 9);
INSERT INTO options (options_id, options_value, poll_id) VALUES (30, 'Pizza', 10);
INSERT INTO options (options_id, options_value, poll_id) VALUES (31, 'French fries', 10);
INSERT INTO options (options_id, options_value, poll_id) VALUES (32, 'Ice cream', 10);
INSERT INTO options (options_id, options_value, poll_id) VALUES (33, 'Beer', 11);
INSERT INTO options (options_id, options_value, poll_id) VALUES (34, 'Wine', 11);
INSERT INTO options (options_id, options_value, poll_id) VALUES (35, 'Cola', 11);
INSERT INTO options (options_id, options_value, poll_id) VALUES (36, 'Beer', 12);
INSERT INTO options (options_id, options_value, poll_id) VALUES (37, 'Wine', 12);
INSERT INTO options (options_id, options_value, poll_id) VALUES (38, 'Cola', 12);
INSERT INTO options (options_id, options_value, poll_id) VALUES (39, 'LeBron James', 13);
INSERT INTO options (options_id, options_value, poll_id) VALUES (40, 'Pete Rose', 13);
INSERT INTO options (options_id, options_value, poll_id) VALUES (41, 'Barry Bonds', 13);
INSERT INTO options (options_id, options_value, poll_id) VALUES (42, 'LeBron James', 14);
INSERT INTO options (options_id, options_value, poll_id) VALUES (43, 'Pete Rose', 14);
INSERT INTO options (options_id, options_value, poll_id) VALUES (44, 'Barry Bonds', 14);
INSERT INTO options (options_id, options_value, poll_id) VALUES (45, 'Rap', 15);
INSERT INTO options (options_id, options_value, poll_id) VALUES (46, 'Country', 15);
INSERT INTO options (options_id, options_value, poll_id) VALUES (47, 'Rock', 15);
INSERT INTO options (options_id, options_value, poll_id) VALUES (48, 'Rap', 16);
INSERT INTO options (options_id, options_value, poll_id) VALUES (49, 'Country', 16);
INSERT INTO options (options_id, options_value, poll_id) VALUES (50, 'Rock', 16);
INSERT INTO options (options_id, options_value, poll_id) VALUES (51, 'New York', 17);
INSERT INTO options (options_id, options_value, poll_id) VALUES (52, 'Pittsburgh', 17);
INSERT INTO options (options_id, options_value, poll_id) VALUES (53, 'San Francisco', 17);